# Generated by Django 4.1.7 on 2023-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="A unique label / key used to identify the IdP to use. (Recommended value is the name or URL of the IdP.)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="The entity ID provided by the IdP.",
                        max_length=255,
                        verbose_name="Entity ID",
                    ),
                ),
                (
                    "sso_url",
                    models.CharField(
                        help_text="The SSO URL provided by the IdP.",
                        max_length=255,
                        verbose_name="SSO URL",
                    ),
                ),
                (
                    "x509_cert",
                    models.TextField(
                        help_text="The X.509 certificate provided by the IdP.",
                        verbose_name="X509 Certificate",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Configuration keys to avoid having to use uniform "
                            "resource name's as attributes to map user details "
                            "required to complete account creation."
                        ),
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
