# Generated by Django 4.1.7 on 2023-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_saml", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprovider",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="The name of the provider (e.g. Google Workspace, Okta).",
                max_length=255,
            ),
        ),
    ]
