# Generated by Django 6.0.3 on 2026-03-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_saml", "0002_identityprovider_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprovider",
            name="requested_authn_context_comparison",
            field=models.CharField(
                choices=[
                    ("EXACT", "Exact"),
                    ("MINIMUM", "Minimum"),
                    ("MAXIMUM", "Maximum"),
                    ("BETTER", "Better"),
                ],
                default="EXACT",
                help_text="RequestedAuthnContext comparison value passed to python3-saml.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="identityprovider",
            name="requested_authn_context_mode",
            field=models.CharField(
                choices=[
                    ("DISABLED", "Disabled"),
                    ("PASSWORD", "PasswordProtectedTransport"),
                    ("CUSTOM", "Custom"),
                ],
                default="DISABLED",
                help_text="How to populate the SAML RequestedAuthnContext for this IdP.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="identityprovider",
            name="requested_authn_context_values",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Custom AuthnContextClassRef values for CUSTOM mode. Ignored for DISABLED and PASSWORD.",
            ),
        ),
    ]
